export const mosqueJsonLd = {
  "@context": "https://schema.org",
  "@type": "Mosque",
  name: "Turkish Islamic Center Canada",
  url: "https://papemosque.ca/",
  email: "info@papecami.com",
  telephone: "+1-647-834-2000",
  address: {
    "@type": "PostalAddress",
    streetAddress: "336 Pape Ave",
    addressLocality: "Toronto",
    addressRegion: "ON",
    postalCode: "M4M 2W7",
    addressCountry: "CA",
  },
  image: "https://papemosque.ca/og.jpeg",
  logo: "https://papemosque.ca/logo.jpeg",
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
      ],
      opens: "00:00",
      closes: "23:59",
    },
  ],
  foundingDate: "1983-04",
  hasMap: "https://maps.app.goo.gl/32uuUt7L7MBrpKUT8",
  areaServed: "Toronto, Ontario, Canada",
  potentialAction: {
    "@type": "DonateAction",
    target: "https://papemosque.ca/donation",
  },
};
