import type { Metadata } from 'next';
import { Lato, Bricolage_Grotesque } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const bricolageGrotesque = Bricolage_Grotesque({
  variable: '--font-bricolage-sans',
  subsets: ['latin'],
});

const lato = Lato({
  weight: '400',
  variable: '--font-lato-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${bricolageGrotesque.variable} antialiased font-sans`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
